apiVersion: v1
kind: Pod
metadata:
  name: nexus-test
  namespace: hotel-backend
spec:
  imagePullSecrets:
    - name: regcred
  containers:
    - name: test
      image: nexus.nexus.svc.cluster.local:8082/backend:latest
      command:
        - sleep
        - "3600"
