name: Pipeline 1 - Docker build and push

on:
  push:
    branches:
      - dev

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Image Tag
        id: image
        shell: powershell
        run: |
          "tag=${{ github.sha }}" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

          # Debugging purposes, show the nexus registry secret value (masked in logs)
      
      - name: Debug registry
        run: |
          echo "${{ secrets.NEXUS_REGISTRY }}" | Out-File registry.txt
          Get-Content registry.txt

      - name: Debug username
        run: |
          echo "Username length:"
          echo "${{ secrets.NEXUS_USERNAME }}".Length

      - name: Check secret lengths
        shell: powershell
        run: |
          Write-Host "Username length: $($env:NEXUS_USERNAME.Length)"
          Write-Host "Password length: $($env:NEXUS_PASSWORD.Length)"
          Write-Host "Registry length: $($env:NEXUS_REGISTRY.Length)"
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          NEXUS_REGISTRY: ${{ secrets.NEXUS_REGISTRY }}

      - name: Debug registry
        run: |
          echo "${{ secrets.NEXUS_REGISTRY }}" | Out-File registry.txt
          Get-Content registry.txt

      - name: Test Nexus login
        shell: powershell
        run: |
          docker logout host.docker.internal:8082
          docker login "${{ secrets.NEXUS_REGISTRY }}" -u "${{ secrets.NEXUS_USERNAME }}" -p "${{ secrets.NEXUS_PASSWORD }}"

      - name: Login to Nexus Docker Registry
        run: |
          docker login "${{ secrets.NEXUS_REGISTRY }}" -u "${{ secrets.NEXUS_USERNAME }}" -p "${{ secrets.NEXUS_PASSWORD }}"

      # Pytest
      # - name: Install test dependencies
      #   run: |
      #     pip install -r requirements.txt

      # - name: Run pytest
      #   run: |
      #     pytest -vv

      - name: Build Docker image
        run: |
          docker build -t "${{ secrets.NEXUS_REGISTRY }}/backend:${{ steps.image.outputs.tag }}" .

      - name: Push Docker image to Nexus
        run: docker push "${{ secrets.NEXUS_REGISTRY }}/backend:${{ steps.image.outputs.tag }}"

      - name: Verify image exists
        run: |
          docker images | Select-String "${{ steps.image.outputs.tag }}"
          