name: Pipeline 2 - Deployment Preparation

on:
  workflow_run:
    workflows:
      - "Pipeline 1 - Build"
    types:
      - completed

jobs:
  update-manifest:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout infra-repo
        uses: actions/checkout@v4
        with:
          repository: gswack/infra-repo
          token: ${{ secrets.PIPELINE_TOKEN }}
          ref: dev
          path: infra-repo

      # - name: Verify image exists in Nexus
      #   shell: powershell
      #   run: |
      #     $tag = "${{ github.event.workflow_run.head_sha }}"

      #     $result = curl.exe `
      #       -u "${{ secrets.NEXUS_USERNAME }}:${{ secrets.NEXUS_PASSWORD }}" `
      #       http://localhost:8082/v2/frontend/tags/list

      #     if ($result -notmatch $tag) {
      #         throw "Image frontend:$tag does not exist in Nexus"
      #     }

      #     Write-Host "Image frontend:$tag exists in Nexus"

      - name: Get image tag
        id: tag
        run: |
          echo "tag=${{ github.event.workflow_run.head_sha }}" >> $GITHUB_OUTPUT
        # echo "tag=${{ github.event.workflow_run.head_sha }}" >> $GITHUB_OUTPUT

      - name: Show tag
        run: |
          echo "Tag = '${{ steps.tag.outputs.tag }}'"

      - name: Debug workspace
        run: |
          pwd
          ls -la
          find . -maxdepth 3

      - name: Update image tag in deployment.yaml
        run: |
          TAG="${{ steps.tag.outputs.tag }}"
          sed -i "s|host\.docker\.internal:8082/backend:.*|host.docker.internal:8082/backend:${TAG}|g" infra-repo/kubernetes/backend/backend-deployment.yaml

      - name: Verify updated manifest
        run: |
          grep "image:" infra-repo/kubernetes/backend/backend-deployment.yaml

      - name: Commit and push changes
        run: |
          cd infra-repo
          git config --global --add safe.directory "$(pwd)"
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add kubernetes/backend/backend-deployment.yaml
          git commit -m "Update backend image tag to SHA tag"
          git push origin dev

      - name: Open Pull Request
        env:
          GH_TOKEN: ${{ secrets.PIPELINE_TOKEN }}
        run: |
          # using the GitHub CLI to create a pull request
          gh pr create --repo gswack/infra-repo --base main --head dev --title "Deploy backend ${{ steps.tag.outputs.tag }}" --body "Automated PR: update backend image tag to ${{ steps.tag.outputs.tag }}"
        #       uses: repo-sync/pull-request@v2
        # with:
        #   source_branch: dev
        #   destination_branch: main
        #   pr_title: "Deploy backend ${{ steps.tag.outputs.tag }}"
        #   pr_body: "Automated PR: update backend image tag to ${{ steps.tag.outputs.tag }}"
        #   github_token: ${{ secrets.PIPELINE_TOKEN }}
          # pr_repository: gswack/infra-repo

      - name: Auto-merge Pull Request
        env:
          GH_TOKEN: ${{ secrets.PIPELINE_TOKEN }}
        run: |
          PR_NUMBER=$(gh pr list --repo gswack/infra-repo --head dev --json number --jq ".[0].number")
          if [ -z "$PR_NUMBER" ]; then
            echo "Error: No open PR found for dev branch."
            exit 1
          fi
          gh pr merge $PR_NUMBER --repo gswack/infra-repo --merge --admin